### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'Siemens.Engineering.Contract, Version=1600.0.3102.1

### ISSUE THREAD

**Issue by illUkc** [Maroder1/Openness_examples_python#6]
Any tips why i cant import ?

My code :
import clr
clr.AddReference('C:\\Program Files\\Siemens\\Automation\\Portal V16\\PublicAPI\\V16\\Siemens.Engineering.dll')
from System.IO import DirectoryInfo, FileInfo
import Siemens.Engineering as tia

Allways getting error :
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?2247af6e-0d00-47a3-87aa-f2b843b4f44b)
---------------------------------------------------------------------------
FileNotFoundException                     Traceback (most recent call last)
Cell In [2], line 4
      2 clr.AddReference('C:\\Program Files\\Siemens\\Automation\\Portal V16\\PublicAPI\\V16\\Siemens.Engineering.dll')
      3 from System.IO import DirectoryInfo, FileInfo
**----> 4 import Siemens.Engineering as tia**

File <frozen importlib._bootstrap>:1178, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1149, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:676, in _load_unlocked(spec)

File <frozen importlib._bootstrap>:573, in module_from_spec(spec)

File <string>:15, in create_module(klass, spec)

FileNotFoundException: Could not load file or assembly 'Siemens.Engineering.Contract, Version=1600.0.3102.1, Culture=neutral, PublicKeyToken=37a18b206f7724a6' or one of its dependencies. The system cannot find the file specified.
File name: 'Siemens.Engineering.Contract, Version=1600.0.3102.1, Culture=neutral, PublicKeyToken=37a18b206f7724a6'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.MethodBase.GetParameterTypes()
   at System.Reflection.MethodBase.FormatNameAndSig(Boolean serialization)
   at System.Reflection.RuntimeConstructorInfo.ToString()
   at Python.Runtime.MethodObject..ctor(MaybeType type, String name, MethodBase[] info, Boolean allow_threads)
...
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by georg9382** [comment]
Hi, 
I was faced with the same problem. But I could fix it for me.

It noticed that fault message on some windows systems, while other ones were working fine.

A had a problem with my python script on that systems. So I went to python consol and executed the commands step by step. This is, where I got this fault message. However I don't get that fault, when I run the script normal like "py script.py". In this case the following command (after import...) was failing, that was supposed to start a TIA session. What I found out was, that it didn't work with default () parameter, but I had to give the parameter explicit.

**Comment by illUkc** [comment]
Thanks for the answer.

Do you have discord?

V V pet., 27. jan. 2023 ob 14:06 je oseba georg9382 <
***@***.***> napisala:

**Comment by georg9382** [comment]
Discord? What do you mean?

**Comment by illUkc** [comment]
Never mind, I hope you are using discord. Can you give me an email then I
have several questions if you can help me about Siemens.Engineering
functions.

V V pet., 27. jan. 2023 ob 16:57 je oseba georg9382 <
***@***.***> napisala:

> Discord? What do you mean?
>
>

**Comment by georg9382** [comment]
😀 sounds like a lot of work. I prefer staying in public. I might not be the best one to support you.

**Comment by illUkc** [comment]
Hey Georg,

I fixed the previous problem. It wasn't working in Jupyter Notebook, but it worked in a .py script. I'm not sure why.

However, I'm now facing a new problem. I'm trying to export HMI tags, but I'm getting an error. Here's my code:

```
processes = tia.TiaPortal.GetProcesses()
process = processes[0]  
mytia = process.Attach()
myproject = mytia.Projects[0]

software_container = tia.IEngineeringServiceProvider(myproject.Devices[1]).GetService[hwf.SoftwareContainer]()
software = software_container.Software   ## error here  

tags_hmi = software.TagFolder.TagTables.Find("test")
```

The error message says: 'NoneType' object has no attribute 'Software'. However, when I check in the Siemens Openness Explorer, I got a code snippet that looks like this: (TiaPortal.Projects[0].Devices[1].GetService<SoftwareContainer>().Software as HmiTarget).TagFolder.TagTables.

Do you have any tips on what might be causing the error?

Also, do you happen to know if there is an HMI discrete alarms function in the V16 .dll? I checked the 2021 manual, and it seems like there is a function for it, but my .dll doesn't seem to have it."

link of manual :
https://cache.industry.siemens.com/dl/files/533/109798533/att_1069908/v1/TIAPortalOpennessenUS_en-US.pdf

**Comment by georg9382** [comment]
Hi, ok, so for your previous problem the same solution helped for you that also worked for me...

For the other problem I have no idea.
