### ISSUE TITLE
File Not found Exception Error

### ISSUE THREAD

**Issue by Shubham78691** [Maroder1/Openness_examples_python#7]
>>> import Siemens.Engineering
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<string>", line 15, in create_module
System.IO.FileNotFoundException: Could not load file or assembly 'Siemens.Engineering.Contract, Version=1501.7.401.1, Culture=neutral, PublicKeyToken=37a18b206f7724a6' or one of its dependencies. The system cannot find the file specified.
File name: 'Siemens.Engineering.Contract, Version=1501.7.401.1, Culture=neutral, PublicKeyToken=37a18b206f7724a6'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.MethodBase.GetParameterTypes()
   at System.Reflection.MethodBase.FormatNameAndSig(Boolean serialization)
   at System.Reflection.RuntimeConstructorInfo.ToString()
   at Python.Runtime.MethodObject..ctor(MaybeType type, String name, MethodBase[] info, Boolean allow_threads)
   at Python.Runtime.ClassManager.GetClassInfo(Type type, ClassBase impl)
   at Python.Runtime.ClassManager.InitClassBase(Type type, ClassBase impl, ReflectedClrType pyType)
   at Python.Runtime.ReflectedClrType.GetOrCreate(Type type)
   at Python.Runtime.ModuleObject.GetAttribute(String name, Boolean guess)
   at Python.Runtime.ModuleObject.LoadNames()
   at Python.Runtime.ImportHook.Import(String modname)
   at Python.Runtime.CLRModule._load_clr_module(PyObject spec)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Please help me with the error above

**Comment by luewh** [comment]
Hello.

Follow this to turn on Assembly binding logging : 
https://stackoverflow.com/questions/255669/how-to-enable-assembly-bind-failure-logging-fusion-in-net
But another problem will appear.

if the problem is about Siemens.Engineering.Contract then add this:
`clr.AddReference('C:\\Program Files\\Siemens\\Automation\\Portal V17\\Bin\\PublicAPI\\Siemens.Engineering.Contract.dll')`
